export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const GET_PROFILE_BY_USERNAME = 'GET_PROFILE_BY_USERNAME';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const GET_SUGGESTED_PROFILES = 'GET_SUGGESTED_PROFILES';

// Posts
export const CREATE_POST = 'CREATE_POST';
export const GET_POSTS = 'GET_POSTS';
export const POST_LOADING = 'POST_LOADING';
export const GET_HOMEPAGE_POSTS = 'GET_HOMEPAGE_POSTS';
export const POST_COMMENT = 'POST_COMMENT';